<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>3.0</Version>
		<OutputPath>..\Out\Autotests\</OutputPath>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>TestAssembly</AssemblyName>
		<RootNamespace>DemoProject</RootNamespace>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.*" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.*" />
		<PackageReference Include="NLog" Version="6.1.*" />
		<PackageReference Include="NUnit" Version="4.5.*" />
		<PackageReference Include="NUnit.Analyzers" Version="4.12.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="[4.6.0]">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ReportPortal.NLog" Version="3.0.0" />
		<PackageReference Include="ReportPortal.Reqnroll" Version="1.6.0" />
		<PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
		<PackageReference Include="RoslynCodeTaskFactory" Version="2.0.7" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="[8.0.*,9.0.0)" />
	</ItemGroup>

	<ItemGroup>
		<None Update="NLog.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Analyzer Include="$(NuGetPackageRoot)stylecop.analyzers\1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
		<Analyzer Include="$(NuGetPackageRoot)stylecop.analyzers\1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
	</ItemGroup>

</Project>